---
extends: default

rules:
    line-length: disable
    new-line-at-end-of-file: disable
    indentation:
        indent-sequences: consistent
    comments-indentation: false
    comments:
        require-starting-space: true
        min-spaces-from-content: 1
    brackets:
        min-spaces-inside: 0
        max-spaces-inside: 1
        max-spaces-inside-empty: 0

ignore: |
    charts/
